name: Sync GitHub to GitLab

on:
  push:
    branches:
      - main  # Change 'main' to your main branch name if different

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository code
        uses: actions/checkout@v2

      - name: Mirror push to GitLab
        run: |
          git remote add origin http://git.int.india.gov.in/gitadmin/demo_project.git
          git push --mirror gitlab
        env:
          GITLAB_TOKEN: ${{ secrets.DEMO }}

